# Generated by Django 4.1.7 on 2023-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='home name')),
                ('text', models.TextField(verbose_name='home text')),
                ('img', models.ImageField(upload_to='images', verbose_name='home image')),
            ],
        ),
    ]
