# Generated by Django 4.1.7 on 2023-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Homes', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logos', 'verbose_name_plural': 'Logo'},
        ),
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Home image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Home name'),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(verbose_name='Home text'),
        ),
    ]
