# Generated by Django 4.1.7 on 2023-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_home_options_alter_logo_options_alter_home_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='button',
            field=models.CharField(default=1, max_length=30, verbose_name='Button name'),
            preserve_default=False,
        ),
    ]
