# Generated by Django 4.1.7 on 2023-03-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_home_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='About page name')),
                ('text', models.TextField(verbose_name='About page text')),
                ('img', models.ImageField(upload_to='images', verbose_name='About page image')),
                ('button', models.CharField(max_length=30, verbose_name='Button name')),
            ],
        ),
    ]
