# Generated by Django 4.1.7 on 2023-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Entries name')),
                ('text', models.TextField(verbose_name='Entries text')),
                ('img', models.ImageField(upload_to='images', verbose_name='Entries image')),
                ('button', models.CharField(max_length=30, verbose_name='Button name')),
            ],
        ),
    ]
